### ISSUE TITLE
Runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by olfway** [awslabs/eks-node-viewer#153]
Starting from version 0.4.0 eks-node-viewer crashes on start:

```
$ ~/bin/eks-node-viewer --version
eks-node-viewer version 0.4.2
commit: b1dcd24fdfbfcfb7e515d9366c876f644634f31f
built at: 2023-07-20T18:27:47Z
built by: goreleaser

$ ~/bin/eks-node-viewer
Caught panic:

runtime error: slice bounds out of range [:-6]

Restoring terminal...

goroutine 1 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/debug/stack.go:16 +0x19
github.com/charmbracelet/bubbletea.(*Program).Run.func1()
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:440 +0x95
panic({0x1d12cc0, 0xc000830090})
	/opt/hostedtoolcache/go/1.20.6/x64/src/runtime/panic.go:890 +0x263
github.com/awslabs/eks-node-viewer/pkg/model.(*UIModel).View(0xc0005b2240)
	/home/runner/work/eks-node-viewer/eks-node-viewer/pkg/model/uimodel.go:106 +0x7b4
github.com/charmbracelet/bubbletea.(*Program).Run(0xc000412240)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:487 +0x6f5
github.com/charmbracelet/bubbletea.(*Program).Start(...)
	/home/runner/go/pkg/mod/github.com/charmbracelet/bubbletea@v0.24.2/tea.go:548
main.main()
	/home/runner/work/eks-node-viewer/eks-node-viewer/cmd/eks-node-viewer/main.go:103 +0x94f

```

Version 0.3.0 working without issues

**Comment by tzneal** [comment]
I can't reproduce this, but added bounds checks that should resolve it regardless in v0.4.3.
